services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/usr/src/app/app
      # Mount the shared “uploads” volume at the path where Flask will save files:
      - uploads:/usr/src/app/app/uploads
    ports:
      - '5000:5000'
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    networks:
      - app-network
    # (No ports: because Nginx will handle port 80)

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - frontend
      - backend
    ports:
      - '80:80'
    networks:
      - app-network
    volumes:
      # Mount the same “uploads” volume under Nginx’s html folder:
      - uploads:/usr/share/nginx/html/uploads

volumes:
  db_data:
  uploads:              # <–– new shared volume for uploads

networks:
  app-network:
    driver: bridge
